name: Deploy Snapshot to GitHubPackages on push to main

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: write

jobs:
  deploy-snapshot:
    runs-on: ubuntu-latest
    if: github.repository == 'evantill/sample-lib'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Setup Java
        uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Build sample-lib
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f # v2
        with:
          gradle-home-cache-cleanup: true
          arguments: build

      - name: Deploy Snapshot
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f # v2
        env:
          ORG_GRADLE_PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_GITHUB_ACTOR: ${{ github.actor }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        with:
          gradle-home-cache-cleanup: true
          arguments: publishAllToGitHubPackages -Dsnapshot=true --stacktrace
